### ISSUE TITLE
How to Dial HTTPS website

### ISSUE THREAD

**Issue by ghost** [wzshiming/httpproxy#1]
I don't know how to Dial with HTTPS/SSL/TLS website using HTTP proxies, could you help me ? :>

**Comment by wzshiming** [comment]
Proxy streaming via HTTP's CONNECT method, The current default Dial is to use that.

https://github.com/wzshiming/httpproxy/blob/3a656c24e6fb3d305588384c131b449a5dfcc188/dialer.go#L105
https://github.com/wzshiming/httpproxy/blob/3a656c24e6fb3d305588384c131b449a5dfcc188/proxy.go#L79
