### ISSUE TITLE
Use net to make HTTP proxy dialer instead of net/http

### ISSUE THREAD

**Issue by ghost** [wzshiming/httpproxy#2]
Seem HTTP Proxy client in golang is slower than in python cuz it use http client to perform CONNECT to proxy, while python use stream socket https://github.com/Anorov/PySocks/blob/master/socks.py#L674, and it faster than golang very much, do you know to do it?

**Comment by wzshiming** [comment]
Since this currently relies on the implementation of the Golang standard library instead of directly processing the stream, there will indeed be some unnecessary performance loss, but it should not be bad, right? How did you test it?
